version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - NPM
jobs:
  build:
    working_directory: ~/package
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Build Package
          command: |
            yarn
            yarn build
      - run:
          name: Deploy Package
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            npm publish
