version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - NPM
      - publish:
          requires:
            - build
          context:
            - NPM
          filters:
            branches:
              only: master
jobs:
  build:
    working_directory: ~/package
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Build Package
          command: |
            yarn
            yarn test
            yarn build

  publish:
    working_directory: ~/package
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Package
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            npm publish
