version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - GITHUB
      - publish:
          requires:
            - build
          context:
            - GITHUB
jobs:
  build:
    working_directory: ~/package
    resource_class: small
    docker:
      - image: cimg/node:24.11.0
    steps:
      - checkout
      - run:
          name: Build Package
          command: |
            yarn
            yarn test
            yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    working_directory: ~/package
    resource_class: small
    docker:
      - image: cimg/node:24.11.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Package
          command: |
            npm install -g npm@latest
            NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            echo "NPM_ID_TOKEN length: ${#NPM_ID_TOKEN}"
            export NPM_ID_TOKEN
            npm publish --loglevel verbose
